---
title: "Projectsub"
author: "Md Farhad Hossain"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## To understand the file content and column just run one dataset so 
```{r}
dataset1<- get(load("Dataset/stim_02_001_P-1.Rdata"))
print(dataset1)

# clumn names 
colnames(dataset1)            

# Types of the 
sapply(dataset1, class)
```


### Combining all dataset to do combine task 
```{r}
# listed All datafiles in one folder 
file_list <- list.files(path = "Dataset", pattern = "\\.Rdata$", full.names = TRUE)


# Initialize the empty list 
all_data_list <- list()

for (f in file_list) {
  obj_name <- load(f)
  df <- get(obj_name)
  participant_id <- as.numeric(sub(".*P-(\\d+).*", "\\1", f)) # Extracting the perticipent id from the file
  df <- cbind(participant_id = participant_id, df)  # Add participant_id as first column
  all_data_list[[length(all_data_list) + 1]] <- df
}
combined_data <- do.call(rbind, all_data_list)
combined_data$Row <- NULL
combined_data <- combined_data[, c("participant_id", setdiff(names(combined_data), "participant_id"))]

#dim(combined_data)                  # number of rows and columns
#head(combined_data)                 # first few rows with participant_id
table(combined_data$participant_id)  # count rows per participant
print("Shape of the dataframe:")
print(dim(combined_data))

# print(head(combined_data, 100))



```
## column selection and cleaning
```{r}

selected_columns <- combined_data[
  , c("participant_id","Timestamp",
      "Anger", "Contempt", "Disgust", "Fear", "Joy", "Sadness", "Surprise",
      "Engagement", "Sentimentality", "Confusion", "Neutral", "Attention",
      "Brow_Furrow", "Brow_Raise", "Cheek_Raise", "Chin_Raise",
      "Eye_Closure", "Eye_Widen", "Inner_Brow_Raise", "Jaw_Drop",
      "Lip_Corner_Depressor", "Lip_Press", "Lip_Pucker", "Lip_Stretch",
      "Lip_Suck", "Lid_Tighten", "Mouth_Open", "Nose_Wrinkle",
      "Smile", "Smirk", "Upper_Lip_Raise",
      "Pitch", "Yaw", "Roll")
]
#"Valence","Dimpler", "Blink","BlinkRate"
Questionaries_t_clean <- selected_columns[rowSums(is.na(selected_columns) | selected_columns == "") != ncol(selected_columns), ]
selected_columns <- selected_columns[selected_columns$participant_id != 1, ]
rownames(selected_columns) <- NULL  # Reset row numbers starting from 1
selected_columns[] <- lapply(selected_columns, function(x) as.numeric(as.character(x)))
selected_columns[is.na(selected_columns)] <- 0
selected_columns <- selected_columns[!apply(selected_columns, 1, function(row) any(row == 0)), ]
selected_columns$time_seconds <- selected_columns$Timestamp / 1000
selected_columns$Timestamp <- NULL # dropping the timestepm column 
rownames(selected_columns) <- NULL  # Reset row numbers
# Create a new dataframe with time_seconds moved to 2nd column
selected_columns <- selected_columns[c("participant_id", "time_seconds", setdiff(names(selected_columns), c("participant_id", "time_seconds")))]

View(selected_columns)
str(selected_columns)


```


### Loading excel file Qustionaries 
```{r}
library(readxl)
library(dplyr)
library(stringr)

# Load the Excel file
Questionaries <- read_excel("Data-to-Bloom-Post-Survey.xlsx", sheet = 2)

# Transpose the data frame
Questionaries_t <- as.data.frame(t(Questionaries))

# The first row after transpose will be the question labels, so set them as column names
colnames(Questionaries_t) <- Questionaries_t[1,]

# Remove the first row now used as headers
Questionaries_t <- Questionaries_t[-1, ]
#rownames(Questionaries_t) <- NULL


Questionaries_t$Participants <- as.numeric(gsub("P", "", Questionaries_t$Participants))

# Remove columns where all values are NA or blank
Questionaries_t <- Questionaries_t[, colSums(is.na(Questionaries_t) | Questionaries_t == "") < nrow(Questionaries_t)]


# str_squish removes unnecessary spaces
colnames(Questionaries_t) <- str_squish(colnames(Questionaries_t))

# Loop through each column in the data frame

for (col in colnames(Questionaries_t)) {
  cat("\n--- Unique values in column:", col, "---\n")
 # print(unique(Questionaries_t[[col]]))
}
# Filter only participants with number between 2 and 28 (assuming 27 participants starting from P2)
cols_to_convert <- c(
  "Participants",
  "Did you remember the details? (on a scale 1-10, 10 the best)",
  "Did you understand the flaw in the argument with Pythagoras and the measuring tape? (scale 1-10)",
  "Was that interesting to you? (on a scale, 1 -10)",
  "After the quiz - how sure were you about the correctness of your answers?",
  "How would you assess your cognitive stress level when reading the cosine-explanation?",
  "On which scale (1-10, 10 meaning you could apply it)"
)
for (col in cols_to_convert) {
  Questionaries_t[[col]] <- as.numeric(Questionaries_t[[col]])
}

# Remove rows where all columns are NA or empty strings
Questionaries_t_clean <- Questionaries_t[rowSums(is.na(Questionaries_t) | Questionaries_t == "") != ncol(Questionaries_t), ]
rownames(Questionaries_t_clean) <- NULL


colnames(Questionaries_t_clean)[colnames(Questionaries_t_clean) == "Participants"] <- "participant_id" # changing the name of participent to participent_id 
print(Questionaries_t_clean)



```




